### ISSUE TITLE
Extension doesn't work for news pages that contain no paragraphs

### ISSUE THREAD

**Issue by nocivix** [krisztianb/seekingalpha-paywall-remover#10]

**Comment by krisztianb** [comment]
Hi. For me it seems to work. But you sometimes need to reload the page several times.

This is the URL I tried: https://seekingalpha.com/article/4717423-celsius-stock-growth-story-not-over

**Comment by almadimate** [comment]
Articles are working but the news aren't. They might changed something again.

**Comment by krisztianb** [comment]
News seem to work for me also.

I tried this URL: https://seekingalpha.com/news/4090502-tsmc-q1-earnings-preview-all-eyes-on-the-ai-boom

**Comment by almadimate** [comment]
Very interesting, some of them really work. I tried to read this several times without success: https://seekingalpha.com/news/4193684-vertiv-beats-q3-estimates-gives-q4-guidance

**Comment by krisztianb** [comment]
You are right. It doesn't work on that page. The extension assumes that there is at least one paragraph in the news/article for which it waits to load. It looks to me that this news article only contains list items. So that might explain why the extension is not working for it.

**Comment by krisztianb** [comment]
Version **1.12** was released which should also work on pages that only contain list items in the article content. 🎉
