### ISSUE TITLE
The add-on isn't removing the paywall

### ISSUE THREAD

**Issue by TuukkaYlaAnttila** [krisztianb/seekingalpha-paywall-remover#2]
Hi, the paywall remover doesn't work for me. 
<img width="1160" alt="Screenshot 2024-06-11 at 21 04 45" src="https://github.com/krisztianb/seekingalpha-paywall-remover/assets/23167866/af5a9198-8d69-4abb-9e6d-3f2c13f50fab">
<img width="687" alt="Screenshot 2024-06-11 at 21 05 55" src="https://github.com/krisztianb/seekingalpha-paywall-remover/assets/23167866/c45480da-1fd0-4351-946f-f8ff596ed465">

**Comment by krisztianb** [comment]
Hi Tuukka. Have you tried deleting cookies and reloading the page?

**Comment by TuukkaYlaAnttila** [comment]
Works. Thank you!

**Comment by TuukkaYlaAnttila** [comment]
Works. Thank you!
