### ISSUE TITLE
Addon is not working anymore

### ISSUE THREAD

**Issue by nocivix** [krisztianb/seekingalpha-paywall-remover#4]
I FOLLOWED SUGGESTIONS, BUT NOT WORKING 

https://seekingalpha.com/news/4150353-accenture-drops-on-report-of-promotion-delays

L
![Capture](https://github.com/user-attachments/assets/6b574c57-8d95-40f7-9ef6-7807120ad9f6)
LAST VERSION ADDED
THX

SEEMS THAT PAYWALL APPEAR DISSAPPEAR AND THEN THE BACKGROUND REMAIN  WHITE

**Comment by krisztianb** [comment]
Thank you for reporting. I can confirm that the extension is no longer working. My guess is that seekingalpha modified their site once again which once again broke the extension. Will have to look into it when I find the time.

**Comment by nocivix** [comment]
thank you SIR

**Comment by krisztianb** [comment]
It was a bit tricky to fix but it should work again once you update to version 1.7. Please try. Thank you.

**Comment by nocivix** [comment]
Thx Sir you are a STAR
