### ISSUE TITLE
Addon is not always working (several page reloads required)

### ISSUE THREAD

**Issue by nocivix** [krisztianb/seekingalpha-paywall-remover#5]
Hi 

Have a look to https://seekingalpha.com/news/4150999-alibaba-unveils-over-100-open-source-ai-models-including-text-to-video-tool

Seems not working THX

**Comment by nhatlaso1** [comment]
I think this will help you.

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ
If you don't have the c compliator, install it.(gcc or clang)

**Comment by nocivix** [comment]
thx , but it is the same, work only if I open Firefox Asset Manager and Go back reloading Page (Often)

**Comment by nocivix** [comment]
:( Nothing Changed after applied the FIX

**Comment by nocivix** [comment]
Auch...

**Comment by krisztianb** [comment]
Hi. It works for me (including the link you posted). Have you tried the steps mentioned on the main page?


- Make sure you have the latest version of the extension installed (you can use the URL about:addons in Firefox)
- Delete all seekingalpha.com cookies in your browser (key combination Ctrl + Alt + Del)
- Reload the page while holding down the SHIFT button (= reload ignoring cached content)

**Comment by krisztianb** [comment]
Update: What I noticed is that sometimes I have to reload the page a couple of times. Might have to look into what is causing that.

**Comment by nocivix** [comment]
YES still not working , I confirm , is very not stable , I have to reload severals time ... I did ALL you suggested , including Fixing  and   I installed Visual Studio on Windows with C++

**Comment by nocivix** [comment]
I also noticed When I reload , I cannot copy the page in memory , seems Copy command is disabled ,

**Comment by krisztianb** [comment]
> and I installed Visual Studio on Windows with C++

There is no need to install anything additionally. The browser extension is running within the browser as JavaScript.

> I also noticed When I reload , I cannot copy the page in memory , seems Copy command is disabled

That is interesting. Maybe they have blocked the clipboard events. I wonder if that can be undone with the extension.

**Comment by nocivix** [comment]
YES can be undone witj another Extension I solved the copy issue

**Comment by Norjak** [comment]
My workaround has been to reload while scrolling down on my mouse wheel. It usually load after 2-3 tries.

**Comment by CCIPM99** [comment]
Hello, I found the extension is still not working.  Refresh page several times but still cannot scroll down page. Thanks for your work.

**Comment by krisztianb** [comment]
Thanks for the notification. I will look into it.

**Comment by krisztianb** [comment]
I updated the add-on. Please update to version 1.8 and see if it is working for you.

**Comment by CCIPM99** [comment]
Working better now. may have to refresh page multiple times.  Seems to help if you hold down SHIFT button while refreshing.
    On Monday, September 30, 2024 at 01:34:54 p.m. PDT, Krisztián Balla ***@***.***> wrote:  
 
 


I updated the add-on. Please update to version 1.8 and see if it is working for you.

**Comment by krisztianb** [comment]
Another update released: 1.9 because SA changed their webpages. I think they are fully aware of this extension and keep changing their website to intentionally break it. 💩

**Comment by almadimate** [comment]
> Another update released: 1.9 because SA changed their webpages. I think they are fully aware of this extension and keep changing their website to intentionally break it. 💩

Is it possible to publish the extension for a closed group somewhere else?

**Comment by krisztianb** [comment]
Maybe I will take it offline and just use it for myself. We will see.

Until then version 1.10 has been released and should work better. Please update and test.

**Comment by CCIPM99** [comment]
Seems to be working pretty good. Not 100%, but 85%.  Thanks 
    On Wednesday, October 2, 2024 at 11:50:49 a.m. PDT, Krisztián Balla ***@***.***> wrote:  
 
 


Maybe I will take it offline and just use it for myself. We will see.

Until then version 1.10 has been released and should work better. Please update and test.
