### ISSUE TITLE
Sort of removes paywall, but browser window disabled

### ISSUE THREAD

**Issue by malenkai** [krisztianb/seekingalpha-paywall-remover#6]
When visiting a site for the first time, the paywall is replaced with a picture of a man chasing a bus.  Clicking "X" on the picture shows the article without the paywall, but you cannot scroll or otherwise interact with the tab, so it only works for very short articles that fit in one window.  Also, only works the first time; reload or open a private window gives you the paywall.  Must exit and restart FF to get above behavior again.

I did all the troubleshooting steps.
FF version 130.0.1 64 bit windows 11
article: https://seekingalpha.com/article/4723568-revance-therapeutics-crown-merger-red-flags

**Comment by krisztianb** [comment]
Thank you for reporting. I will have a look.

**Comment by krisztianb** [comment]
I updated the add-on. Please update to version 1.8 and see if it is working for you.

**Comment by krisztianb** [comment]
I will close this thread as there is already a similar one telling me that the add-on is not working properly.
Feel free to respond there: #4
