### ISSUE TITLE
Scroll BAR , not working ? When article is long

### ISSUE THREAD

**Issue by nocivix** [krisztianb/seekingalpha-paywall-remover#8]
THX the last version work better, there is an Issue, at least for me , IF the Article is very long, the right scroll Bar disapper and I have to Zoom to read the article ?

as an example https://seekingalpha.com/article/4722691-adobe-generative-credits-offer-a-direct-path-to-ai-driven-profitability

THX

**Comment by krisztianb** [comment]
Could you check that you have version 1.9 installed? I fixed this yesterday.

**Comment by nocivix** [comment]
thx a lot

**Comment by nocivix** [comment]
I did , I confirm my Issue, in case this problem can help you to solve the Trick THX

**Comment by krisztianb** [comment]
Scrolling doesn't work because they've now renamed the class here: https://github.com/krisztianb/seekingalpha-paywall-remover/blob/main/paywall-remover.js#L70

to `scrollLocked`. :smile:

**Comment by nocivix** [comment]
Is required an Update ?

**Comment by krisztianb** [comment]
Yes. Fixed in version 1.10.
