### ISSUE TITLE
seems not working

### ISSUE THREAD

**Issue by hcapp01** [krisztianb/seekingalpha-paywall-remover#9]
seems not working

https://seekingalpha.com/article/4726237-taiwan-semiconductor-one-of-the-best-and-cheapest-ai-plays

<img width="1421" alt="image" src="https://github.com/user-attachments/assets/de210565-8225-44ea-9eb5-7b1455db7425">

**Comment by krisztianb** [comment]
Hi. Unfortunately you often have to reload the page several times to have the pay wall removed. I would need to debug more into this to understand why the mutation observer sometimes doesn't catch the loading of the pay wall correctly.
